---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tigris)
library(data.table)
```

## Census 2010-2021 Counties VA, DC, MD

```{r}
for (i in 10:21) {
  yr <- as.integer(paste0(20, i))
  counties <- counties(state = c("51", "11", "24"), cb = FALSE, year = yr)
  counties$geometry <- NULL
  assign(paste0("dc.counties.", yr), setDT(counties))
}

```

```{r}
if(exists("dt_out")) rm(dt_out)
for (i in 10:21) {
  yr <- as.integer(paste0(20, i))
  cols <- colnames(get(paste0("dc.counties.", yr)))
  cols <- cols[cols %like% "GEOID" | cols %like% "NAMELSAD"]
  dt <- get(paste0("dc.counties.", yr))
  select_cols <- dt[ , cols, with=FALSE]
  colnames(select_cols) <- c("geoid", "region_name")
  select_cols$year <- yr
  
  if(exists("dt_out")) dt_out <- rbindlist(list(dt_out, select_cols))
  else dt_out <- select_cols
}
dc_county_names <- dt_out

dc_county_names[geoid %like% "^51", region_name := paste0(region_name, ", Virginia")]
dc_county_names[geoid %like% "^24", region_name := paste0(region_name, ", Maryland")]
```

## Census 2010-2021 Census Tracts VA, DC, MD

```{r}
for (i in 10:21) {
  yr <- as.integer(paste0(20, i))
  state_fips <- c("51", "11", "24")
  if(exists("dt_out")) rm(dt_out)
  for (s in state_fips) {
    state_tracts <- tracts(state = s, year = yr)
    state_tracts$geometry <- NULL
    setDT(state_tracts)
    if(exists("dt_out")) dt_out <- rbindlist(list(dt_out, state_tracts))
    else dt_out <- state_tracts
  }
  assign(paste0("dc.tracts.", yr), dt_out)
}

```

```{r}
if(exists("dt_out")) rm(dt_out)
for (i in 10:21) {
  yr <- as.integer(paste0(20, i))
  cols <- colnames(get(paste0("dc.tracts.", yr)))
  cols <- cols[cols %like% "GEOID" | cols %like% "NAMELSAD"]
  dt <- get(paste0("dc.tracts.", yr))
  select_cols <- dt[ , cols, with=FALSE]
  colnames(select_cols) <- c("geoid", "region_name")
  select_cols$year <- yr
  
  if(exists("dt_out")) dt_out <- rbindlist(list(dt_out, select_cols))
  else dt_out <- select_cols
}
dc_tract_names <- dt_out
```

```{r}
dc_tract_names$geoid5 <- substr(dc_tract_names$geoid, 1, 5)
dc_counties_unq <- unique(dc_county_names[, .(geoid, region_name)])
mrg <- merge(dc_tract_names, dc_counties_unq, by.x = "geoid5", by.y = "geoid")
mrg[, region_name := paste0(region_name.x, ", ", region_name.y)]
dc_tract_names <- mrg[, .(geoid, region_name, year)]
```

## Census 2010-2021 Census Block Groups VA, DC, MD

```{r}
state_county_fips <- data.table(geoid_st = substr(dc_counties_unq$geoid, 1, 2),
                                geoid_ct = substr(dc_counties_unq$geoid, 3, 5))

if(exists("dt_out")) rm(dt_out)
for (i in 10:21) {
  yr <- as.integer(paste0(20, i))
  for (i in 1:nrow(state_county_fips)) {
    bgs <- block_groups(state = state_county_fips[i, geoid_st],
                        county = state_county_fips[i, geoid_ct],
                        year = yr)
    bgs$geometry <- NULL
    setDT(bgs)
    cols <- colnames(bgs)
    cols <- cols[cols %like% "GEOID" | cols %like% "NAMELSAD"]
    select_cols <- bgs[ , cols, with=FALSE]
    colnames(select_cols) <- c("geoid", "region_name")
    select_cols$year <- yr
    
    if (exists("dt_out")) dt_out <- rbindlist(list(dt_out, select_cols))
    else dt_out <- select_cols
  }
}
dc_block_group_names <- dt_out
```

```{r}
dc_block_group_names$geoid11 <- substr(dc_block_group_names$geoid, 1, 11)
dc_tracts_unq <- unique(dc_tract_names[, .(geoid, region_name)])
mrg <- merge(dc_block_group_names, dc_tracts_unq, by.x = "geoid11", by.y = "geoid")
mrg[, region_name := paste0(region_name.x, ", ", region_name.y)]
dc_block_group_names <- mrg[, .(geoid, region_name, year)]
```

## Combine

```{r}
census_geo_names <- rbindlist(list(dc_county_names, dc_tract_names, dc_block_group_names))
census_geo_names <- unique(census_geo_names[, .(geoid, region_name)])

census_geo_names[nchar(geoid)==5, region_type := "county"]
census_geo_names[nchar(geoid)==11, region_type := "tract"]
census_geo_names[nchar(geoid)==12, region_type := "block group"]
```

## Write to DB

```{r}
con <- get_db_conn()
dc_dbWriteTable(con, "dc_geographies", "ncr_cttrbg_tiger_2010_2020_geo_names", census_geo_names)
DBI::dbDisconnect(con)
```
