---
title: "Create Datafile"
author: "Joanna Schroeder"
date: "01/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get dataset DOI

```{r}
dataset_doi <- readLines(here::here("data/dataset_doi"))[1]
```

## Code you used to create dataset

measures_info.json: build_measure_info.R

```{r data}
```

## Write to compressed file

```{r compress}
#write_json(vdh_measure_info, "data/vdh_measure_info.json")
all_geos_file_name = "vdh_measure_info"
dat_file_path = here::here(paste0("data/", all_geos_file_name, ".json"))
```

## Upload Files to Dataverse Dataset

```{r upload}
# check if file already exists

file_names <- dataverse::dataset_files(
    dataset = dataset_doi,
    version = ":latest",
    key = Sys.getenv("DATAVERSE_KEY"),
    server = Sys.getenv("DATAVERSE_SERVER")
)

names <- c()

if (length(file_names) > 0)
{
  for(i in 1:length(file_names))
  {
    names <- c(names, file_names[[i]]$dataFile$filename)
  }

} else
{
  names <- file_names
}


if (paste0(all_geos_file_name, ".json") %in% names) # file already exists, so we update it
{
   idx = which(names == paste0(all_geos_file_name, ".json"))
  
   dataverse::update_dataset_file(
     file = dat_file_path,
     dataset = dataset_doi,
     id = file_names[[idx]]$dataFile$id,
     key = Sys.getenv("DATAVERSE_KEY"),
     server   = Sys.getenv("DATAVERSE_SERVER"),
     description = all_geos_file_name
   )
   
} else  # file doesn't exist, so we add it to the dataset
{
   dataverse::add_dataset_file(
     file = dat_file_path,
     dataset = dataset_doi,
     key = Sys.getenv("DATAVERSE_KEY"),
     server   = Sys.getenv("DATAVERSE_SERVER"),
     description = all_geos_file_name
   )
}

```
